
fastlane_version "1.90.0"

default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scheme "FieryTest"
    scan
  end

end
