
fastlane_version "1.90.0"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do

    scan(scheme: "FieryTest")

    slather(
      build_directory: '/Users/travis/Library/Developer/Xcode/DerivedData',
      scheme: 'FieryTest',
      workspace: 'Fiery.xcworkspace'
    )

  end

  desc "TestFlight AdHoc Build"
  lane :testflight do

    increment_build_number

    match(type: "adhoc")

    gym(
	export_method: "app-store",
	scheme: "Fiery", 
	workspace: "Fiery.xcworkspace"
	)

    pilot

  end

end
