
fastlane_version "1.85.0"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "FieryTest")
  end

  desc "TestFlight AdHoc Build"
  lane :testflight do

    increment_build_number

    scan(scheme: "FieryAdhoc")

    match(
	app_identifier: "app.ragnar.Fiery.ad-hoc", 
	type: "adhoc"
	)

    gym(
	configuration: "Ad Hoc",
	scheme: "FieryAdhoc", 
	workspace: "Fiery.xcworkspace"
	)

    pilot

  end

end
